"use client";
import { useEffect, useState } from "react";
import { RequireSession } from "../../components/RequireSession";
import { apiGet, type TeachersResponse, type WorkflowResponse } from "../../lib/api";
export default function ClassesTeachersPage() {
  const [teachers, setTeachers] = useState<TeachersResponse | null>(null); const [workflow, setWorkflow] = useState<WorkflowResponse | null>(null);
  useEffect(() => { Promise.all([apiGet<TeachersResponse>("/api/v1/teachers"), apiGet<WorkflowResponse>("/api/v1/workflow")]).then(([teacherData, workflowData]) => { setTeachers(teacherData); setWorkflow(workflowData); }).catch(() => undefined); }, []);
  const sync = workflow?.synchronization.status;
  return <RequireSession>{() => <><section className="card"><h2>Classes & teachers</h2><p className="muted">Teaching assignments are owned in Scholaroscope and synchronized automatically.</p><div className={`sync-state ${sync === "FAILED" ? "error" : ""}`}><strong>{sync === "PENDING" ? "Synchronization pending" : sync === "FAILED" ? "Synchronization failed" : sync === "NO_ASSIGNMENTS_IN_SCHOLAROSCOPE" ? "No teachers assigned in Scholaroscope" : sync === "SUCCEEDED_NO_ELIGIBLE_ASSIGNMENTS" ? "No eligible teaching assignments" : "Teaching assignments synchronized"}</strong><p>{sync === "NO_ASSIGNMENTS_IN_SCHOLAROSCOPE" ? "Assign teachers to class subjects in Scholaroscope, then refresh this workspace." : sync === "SUCCEEDED_NO_ELIGIBLE_ASSIGNMENTS" ? "Assignments exist, but their teachers, class subjects, or curriculum setup are not currently eligible for scheduling." : sync === "FAILED" ? "Return to Scholaroscope and request an academic data refresh, or contact support if it continues." : sync === "PENDING" ? "Academic data is still being synchronized. Refresh from Scholaroscope if this does not finish shortly." : `${workflow?.progress.assignments ?? 0} active assignments are ready for scheduling.`}</p></div></section><section className="card"><h3>Teachers</h3>{!teachers?.teachers.length ? <div className="empty">No assigned teachers are available. Managers are not listed unless they also hold an active teaching assignment.</div> : <div className="teacher-list">{teachers.teachers.map((teacher) => <article key={teacher.actor_uuid}><strong>{teacher.display_name}</strong><ul>{teacher.assignments.map((assignment) => <li key={assignment.cohort_subject_uuid}>{assignment.cohort_name} · {assignment.subject_name}</li>)}</ul></article>)}</div>}</section></>}</RequireSession>;
}
