"use client";
import { useEffect, useState } from "react";
import { RequireSession } from "../../components/RequireSession";
import { apiGet, apiSend, type AcademicContextResponse, type ClassesSpacesResponse } from "../../lib/api";
export default function ClassesSpacesPage() {
  const [term, setTerm] = useState(""); const [data, setData] = useState<ClassesSpacesResponse | null>(null); const [name, setName] = useState(""); const [kind, setKind] = useState("SPECIALIZED"); const [error, setError] = useState<string | null>(null);
  const load = (termUuid = term) => { if (termUuid) apiGet<ClassesSpacesResponse>(`/api/v1/classes-spaces?term_uuid=${termUuid}`).then(setData).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Classes and spaces could not be loaded.")); };
  // Initial academic context chooses the server-derived active term.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { apiGet<AcademicContextResponse>("/api/v1/academic-context").then((context) => { const selected = context.selected_term?.term_uuid ?? ""; setTerm(selected); load(selected); }).catch(() => undefined); }, []);
  return <RequireSession>{() => <><section className="card"><h2>Classes & spaces</h2><p className="muted">Classes come from Scholaroscope. Physical rooms are optional scheduling resources and never replace a class.</p>{error ? <div className="error">{error}</div> : null}<h3>Synchronized classes ({data?.class_count ?? 0})</h3>{!data?.classes.length ? <div className="empty">No active classes are synchronized for this term.</div> : <div className="class-list">{data.classes.map((item) => <article key={item.cohort_uuid}><div><strong>{item.name}</strong><span>{item.enrollment_count} enrolled learners</span></div><label>Ordinary classroom<select value={item.default_room_uuid} onChange={(event) => apiSend(`/api/v1/classes/${item.cohort_uuid}/default-room`, "PATCH", { room_uuid: event.target.value }).then(() => load()).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Classroom could not be updated."))}><option value="">No default physical room</option>{data.spaces.filter((space) => space.status === "ACTIVE").map((space) => <option key={space.room_uuid} value={space.room_uuid}>{space.name}</option>)}</select></label></article>)}</div>}</section><section className="card"><h3>Optional physical spaces</h3><p className="muted">Add shared or specialized facilities only when lessons need them.</p><div className="toolbar"><input value={name} onChange={(event) => setName(event.target.value)} placeholder="e.g. Science Laboratory"/><select value={kind} onChange={(event) => setKind(event.target.value)}><option value="SPECIALIZED">Specialized facility</option><option value="SHARED">Shared room</option><option value="GENERAL">General classroom</option></select><button disabled={!name.trim()} onClick={() => apiSend("/api/v1/rooms", "POST", { name, kind, exclusive: true }).then(() => { setName(""); load(); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Space could not be saved."))}>Add space</button></div>{!data?.spaces.length ? <div className="empty">No optional physical spaces configured. This is valid.</div> : <div className="space-list">{data.spaces.map((space) => <article key={space.room_uuid}><div><strong>{space.name}</strong><span>{space.kind.toLowerCase()} · {space.capacity ? `capacity ${space.capacity}` : "capacity not set"}</span></div><button onClick={() => apiSend(`/api/v1/rooms/${space.room_uuid}`, "PATCH", { status: space.status === "ACTIVE" ? "DISABLED" : "ACTIVE" }).then(() => load()).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Space could not be updated."))}>{space.status === "ACTIVE" ? "Deactivate" : "Reactivate"}</button><button onClick={() => apiSend(`/api/v1/rooms/${space.room_uuid}`, "DELETE").then(() => load()).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Space could not be deleted."))}>Delete</button></article>)}</div>}</section></>}</RequireSession>;
}
